### ISSUE TITLE
[portal] handle ^C in jobs.py commands

### ISSUE THREAD

**Issue by ericsnowcurrently** [faster-cpython/tools#39]
Currently we do not handle `^C` in any of the jobs.py commands.  `KeyboardInterrupt` goes uncaught, a traceback is printed, and the script exits.  Instead we could print a helpful message, optionally do some cleanup, and then exit.

- [ ] list
- [ ] show
- [ ] add  (cleanup: delete up the request files)
- [ ] run  (cleanup: unqueue or cancel the job)
- [ ] attach - #38
- [ ] cancel

(We may or may not do this for jobs-dev.py commands too.)

**Comment by gvanrossum** [comment]
Why would you ^C any of these commands? Because somehow it's stuck? Or because you changed your mind? If the latter, the proposed behavior sounds fine. OTOH if it's the former the traceback might actually be somewhat helpful ("why is it stuck"? "Oh the remote crashed"). So then we'd need an option to still get the tracebacks. Or maybe cleaning up some files is all we need, and the traceback is harmless?

**Comment by ericsnowcurrently** [comment]
> Why would you ^C any of these commands? Because somehow it's stuck? Or because you changed your mind?

My motivation was the latter.  I had not considered the "stuck" case.  I hadn't really run into that before and expect it's unlikely to happen in the future.

Realistically, the only meaningful thing we would do for `^C` with any of the commands is hide the traceback.  For the few cases where we would do cleanup, the commands complete fast enough that we're unlikely to hit the interval where cleanup matters.

The only command where `^C` is actually meaningful is "attach", which is already covered by #38.

So let's just close this issue.  We can re-open later if it ends up mattering.
